spring:
  application:
    name: zuul-api-gateway

  profiles:
    active: dev

# Eureka Client
eureka:
  client:
    # 是否将自己注册到Eureka服务中, default: true
    register-with-eureka: true
    # 是否从Eureka中获取注册信息, default: true
    fetch-registry: true
    # Eureka client 与 server 交互地址(已配置安全认证)
    service-url:
      # 集群时, 可指定一个, 也可指定多个(","隔开)
      defaultZone: http://administrator:omega@10.46.31.101:8000/eureka/
  instance:
    # 将ip注册到Eureka中
    prefer-ip-address: true
    ip-address: 10.46.31.101