spring:
  application:
    name: zuul-api-gateway

  #profiles:
    #active: dev

zuul:
  # 转发所有header(全局路由)
  #sensitive-headers: '*'

  # 默认配置，请求很容易超时com.netflix.zuul.exception.zuulexception timeout
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

# 默认配置，请求很容易超时com.netflix.zuul.exception.zuulexception timeout
##timeout config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1

