spring:
  application:
    name: zuul-api-gateway

  #profiles:
    #active: dev

zuul:
  # 转发所有header(全局路由)
  #sensitive-headers: '*'

  # 默认配置时，请求很容易超时com.netflix.zuul.exception.zuulexception timeout
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

# 断路器的超时时间需要大于ribbon的超时时间, 否则不会触发重试
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  # 请求处理的超时时间
  ReadTimeout: 10000
  # 请求连接的超时时间
  ConnectTimeout: 10000
  # 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  # 当前实例的重试次数
  MaxAutoRetries: 3
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 3

