spring:
  application:
    name: zuul-api-gateway

  profiles:
    active: dev

# Eureka Client
eureka:
  client:
    # \u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230Eureka\u670D\u52A1\u4E2D, default: true
    register-with-eureka: true
    # \u662F\u5426\u4ECEEureka\u4E2D\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F, default: true
    fetch-registry: true
    # Eureka client \u4E0E server \u4EA4\u4E92\u5730\u5740(\u5DF2\u914D\u7F6E\u5B89\u5168\u8BA4\u8BC1)
    service-url:
      # \u96C6\u7FA4\u65F6, \u53EF\u6307\u5B9A\u4E00\u4E2A, \u4E5F\u53EF\u6307\u5B9A\u591A\u4E2A(","\u9694\u5F00)
      defaultZone: http://administrator:omega@127.0.0.1:6868/eureka/
  instance:
    # \u5C06ip\u6CE8\u518C\u5230Eureka\u4E2D
    prefer-ip-address: true